Heart disease

In [1]:
# Load the dataset
import pandas as pd
import numpy as np
df = pd.read_csv("heart_disease.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
# Handle missing values appropriately.
df.isnull().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [3]:
# Encode categorical variables (e.g., gender) using one-hot encoding.
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [4]:
# Scale numerical features (e.g., age, cholesterol, blood pressure).

In [5]:
# .Perform basic exploratory data analysis to understand the distribution of the data and relationships between variables.
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,52.833333,0.766667,1.466667,136.400000,232.133333,0.166667,0.633333,160.366667,0.266667,1.183333,1.533333,0.500000,1.966667,0.900000
std,8.594639,0.430183,1.166585,14.075168,38.690401,0.379049,0.490133,17.391007,0.449776,1.361562,0.730297,0.900192,0.490133,0.305129
min,37.000000,0.000000,0.000000,110.000000,164.000000,0.000000,0.000000,108.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,45.750000,1.000000,0.000000,130.000000,204.500000,0.000000,0.000000,150.500000,0.000000,0.075000,1.000000,0.000000,2.000000,1.000000
50%,53.500000,1.000000,2.000000,140.000000,233.500000,0.000000,1.000000,163.000000,0.000000,0.900000,2.000000,0.000000,2.000000,1.000000
75%,58.750000,1.000000,2.000000,143.750000,246.250000,0.000000,1.000000,174.250000,0.750000,1.500000,2.000000,1.000000,2.000000,1.000000
max,71.000000,1.000000,3.000000,160.000000,354.000000,1.000000,1.000000,187.000000,1.000000,6.200000,2.000000,3.000000,3.000000,1.000000

In [6]:
# Visualize correlations between features and the target variable (presence or absence of heart disease)
corr = df.corr()
corr

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.141453,0.173107,0.167324,0.120670,0.199345,-0.129608,-0.529959,0.190299,0.118507,-0.210597,0.608376,0.088679,0.256405
sex,-0.141453,1.000000,0.224459,0.198187,-0.008425,0.246718,-0.092675,-0.154100,0.154456,-0.089290,-0.139031,-0.222615,-0.201705,0.078811
cp,0.173107,0.224459,1.000000,0.103743,-0.113731,0.285931,-0.353805,-0.176991,0.148962,0.213476,-0.464113,0.197016,0.088451,0.038749
trestbps,0.167324,0.198187,0.103743,1.000000,-0.125350,0.342554,-0.297907,-0.429715,0.320279,0.222757,-0.276424,0.220444,-0.232928,-0.006423
chol,0.120670,-0.008425,-0.113731,-0.125350,1.000000,-0.201426,-0.050066,0.012378,0.233689,-0.233444,0.173133,0.006930,0.000242,0.208552
fbs,0.199345,0.246718,0.285931,0.342554,-0.201426,1.000000,-0.587754,-0.302524,0.134840,0.052338,-0.332182,-0.151587,-0.711491,0.149071
restecg,-0.129608,-0.092675,-0.353805,-0.297907,-0.050066,-0.587754,1.000000,0.226678,-0.010428,0.119706,0.083491,0.039077,0.521531,-0.023057
thalach,-0.529959,-0.154100,-0.176991,-0.429715,0.012378,-0.302524,0.226678,1.000000,-0.493446,-0.218755,0.263722,-0.606826,-0.018744,-0.129315
exang,0.190299,0.154456,0.148962,0.320279,0.233689,0.134840,-0.010428,-0.493446,1.000000,0.170800,-0.342934,0.255500,0.041712,-0.050252
oldpeak,0.118507,-0.089290,0.213476,0.222757,-0.233444,0.052338,0.119706,-0.218755,0.170800,1.000000,-0.826514,0.493750,0.340171,0.095451
slope,-0.210597,-0.139031,-0.464113,-0.276424,0.173133,-0.332182,0.083491,0.263722,-0.342934,-0.826514,1.000000,-0.367169,-0.044957,-0.061898
ca,0.608376,-0.222615,0.197016,0.220444,0.006930,-0.151587,0.039077,-0.606826,0.255500,0.493750,-0.367169,1.000000,0.508004,0.188311
thal,0.088679,-0.201705,0.088451,-0.232928,0.000242,-0.711491,0.521531,-0.018744,0.041712,0.340171,-0.044957,0.508004,1.000000,-0.023057
target,0.256405,0.078811,0.038749,-0.006423,0.208552,0.149071,-0.023057,-0.129315,-0.050252,0.095451,-0.061898,0.188311,-0.023057,1.000000

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize = (20,10))
sns.heatmap(corr, annot=True)

In [ ]:
# Split the data into training and testing sets (e.g., 80% training, 20% testing).
from sklearn.model_selection import train_test_split
x = df[['age','sex',	'cp','trestbps', 'chol','fbs','restecg','thalach','exang','oldpeak'	,'slope','ca','thal']]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 42)

In [ ]:
# Train a logistic regression model on the training set.
# Ensure that you include regularization (L1, L2, or both) in your model to prevent overfitting.
from sklearn.linear_model import LogisticRegression
model= LogisticRegression(penalty='l1', solver='liblinear')
model.fit(X_train, y_train)

In [ ]:
# Evaluate the model using accuracy, precision, recall, F1-score, and ROC-AUC on the test set.
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, classification_report
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# # Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

# # Print the results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("ROC-AUC:", roc_auc)

In [ ]:
# Plot the ROC curve and calculate the AUC value.
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

In [ ]:
# Interpret the coefficients of the logistic regression model.
coefficients = model.coef_[0]
feature_names = x.columns
coefficients_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})
print(coefficients_df.sort_values(by='Coefficient', ascending=False))

In [ ]:
# Calculate the odds ratios for the features and explain what they imply about the likelihood of having heart disease.
import numpy as np
coefficients = model.coef_[0]
feature_names = x.columns

# Calculate odds ratios (exponentiate coefficients)
odds_ratios = np.exp(coefficients)

# Create a DataFrame to store feature names and corresponding odds ratios
odds_ratios_df = pd.DataFrame({'Feature': feature_names, 'Odds Ratio': odds_ratios})

# Print the odds ratios sorted by magnitude
print(odds_ratios_df.sort_values(by='Odds Ratio', ascending=False))